"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

add_newline = false

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 0

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "yellow"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = ""

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[cmd_duration]
min_time = 10_000

[status]
disabled = false
format = "[\\[$status\\]]($style) "
style = "red"

[nodejs]
disabled = true

[package]
disabled = true
